In [ ]:
# -*- coding: utf-8 -*-
"""worksheet1.ipynb"""

import numpy as np
empty_array=np.array((2,2))
print("empty array of 2*2:",empty_array)
ones_array = np.ones((4, 2))
print("All-One Array 4*2:", ones_array)
filled_array=np.full((4,4),8,dtype=float)
print("filled array with shape and type:",filled_array)
given_array = np.array([[[1, 2], [3, 4],[5,6]]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros like given array:", given_array)
ones_like_array = np.ones_like(given_array)
print(" Ones like given array:", ones_like_array)
list1 = [1, 2, 3, 4]
array_from_list = np.array(list1)
print(" Numpy array from list:", array_from_list)

import numpy as np
array=np.arange(10,50)
print("arrays with values ranging 10 to 49:",array)
matrix = np.arange(9).reshape(3, 3)
print(" 3x3 Matrix 0 to 8:\n", matrix)
identity = np.eye(3)
print(" 3x3 Identity Matrix:\n", identity)
random_array = np.random.random(30)
mean4 = random_array.mean()
print(" Random Array of size 30:\n", random_array)
print("Mean:", mean4)
random_matrix = np.random.random((10, 10))
min5 = random_matrix.min()
max5 = random_matrix.max()
print(" 10x10 Random Array:\n", random_matrix)
print("Minimum:", min5)
print("Maximum:", max5)
zero_array = np.zeros(10)
zero_array[4] = 1
print(" Zero array with 5th element as 1:\n", zero_array)
arr = np.array([1,2,0,0,4,0])
reversed = arr[::-1]
print(" Reversed Array:\n", reversed)
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(" 2D array with 1 on border and 0 inside:\n", border)
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(" 8x8 Checkerboard Pattern:\n", checker)

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_xy = x + y
print(" x + y:\n", add_xy)

sub_xy = x - y
print(" x - y:\n", sub_xy)

mul_x = x * 3
print(" x * 3:\n", mul_x)

square_x = x ** 2
print(" Square of x:\n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(" Dot products:")
print("v . w =", dot_vw)
print("x . v =", dot_xv)
print("x . y =\n", dot_xy)

concat_row_xy = np.concatenate((x, y), axis=0)
concat_col_vw = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print(" Concatenate:")
print("x and y along row:\n", concat_row_xy)
print("v and w along column:\n", concat_col_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(" Error concatenating x and v:", e)
    print("Explanation: x is 2x2 and v is 1D array with shape (2,). Shapes are incompatible along axis 0.")

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print(" A * A_inv:\n", identity_check)
AB = np.dot(A, B)
BA = np.dot(B, A)
print(" AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.allclose(AB, BA))

AB_T = (AB).T
BT_AT = np.dot(B.T, A.T)
print(" (AB)^T = B^T A^T?\n", np.allclose(AB_T, BT_AT))

# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution of the system using inverse:\n", X)

X_solve = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve:\n", X_solve)

empty array of 2*2: [2 2]
All-One Array 4*2: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
filled array with shape and type: [[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
Zeros like given array: [[[1 2]
  [3 4]
  [5 6]]]
 Ones like given array: [[[1 1]
  [1 1]
  [1 1]]]
 Numpy array from list: [1 2 3 4]
arrays with values ranging 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 Random Array of size 30:
 [0.33124101 0.71468134 0.19752203 0.35760527 0.33471605 0.72243532
 0.77066462 0.2251103  0.70510794 0.4761346  0.1828523  0.56689396
 0.64513605 0.82641163 0.21986723 0.26041472 0.83855507 0.48970004
 0.91192596 0.46710557 0.37464976 0.18109151 0.09465814 0.54371331
 0.09391845 0.54786431 0.45230942 0.85068396 0.61369954 0.35348862]
Mean: 0.47833860116826943
 10x10 Random Array:
 [[0.65996